# Theme 1: Minimaliste Épuré
colors {
	background #000000
	statusline #ffffff
	separator #333333

	# name             border     background  text
	focused_workspace  #000000    #0088ff     #ffffff
	active_workspace   #333333    #000000     #888888
	inactive_workspace #333333    #000000     #555555
	urgent_workspace   #ff0055    #000000     #ff0055
	binding_mode       #ffaa00    #000000     #ffaa00
}

