# Theme 4: Material Design
colors {
	background #212121
	statusline #e0e0e0
	separator #383838

	# name             border     background  text
	focused_workspace  #2196f3    #2196f3     #212121
	active_workspace   #757575    #303030     #e0e0e0
	inactive_workspace #424242    #212121     #757575
	urgent_workspace   #f44336    #212121     #f44336
	binding_mode       #ff9800    #212121     #ff9800
}

