# Theme 5: Solarized Dark
colors {
	background #002b36
	statusline #93a1a1
	separator #073642

	# name             border     background  text
	focused_workspace  #268bd2    #268bd2     #002b36
	active_workspace   #859900    #073642     #859900
	inactive_workspace #586e75    #002b36     #586e75
	urgent_workspace   #dc322f    #002b36     #dc322f
	binding_mode       #b58900    #002b36     #b58900
}

