# Theme 6: Gruvbox Modern
colors {
	background #1d2021
	statusline #ebdbb2
	separator #3c3836

	# name             border     background  text
	focused_workspace  #ebdbb2    #d79921     #1d2021
	active_workspace   #a89984    #32302f     #ebdbb2
	inactive_workspace #665c54    #1d2021     #928374
	urgent_workspace   #fb4934    #1d2021     #fb4934
	binding_mode       #b8bb26    #1d2021     #b8bb26
}

