################ CUSTOM CONFIG ################

exec --no-startup-id discord --start-minimized
#exec --no-startup-id signal-desktop --start-in-tray

# Workspaces assignation
assign [class="^Alacritty"] $ws1
for_window [class="^Alacritty"] focus

assign [class="^jetbrains-.+"] $ws2
for_window [class="^jetbrains-.+"] focus

assign [class="Code+"] $ws2
for_window [class="Code+"] focus

assign [class="Firefox"] $ws3
for_window [class="Firefox"] focus

assign [class="Google-chrome"] $ws3
for_window [class="Google-chrome"] focus

assign [class="discord+"] $ws5
for_window [class="discord+"] focus

assign [class="Slack+"] $ws5
assign [class="Signal+"] $ws5
for_window [class="Slack+"] focus
for_window [class="Signal+"] focus

assign [class="VirtualBox"] $ws10
for_window [class="VirtualBox"] focus

bindsym $mod+Ctrl+n exec --no-startup-id i3-sensible-terminal -e spf 

