#!/usr/bin/env perl

use strict;
use warnings;
use POSIX qw/strftime/;
use utf8;

# Configuration du format :
# %d = Jour (07)
# %B = Mois complet (mars)
# %Y = Année (2026)
my $format = "%d %B %Y";

# Force l'encodage UTF-8 pour les mois accentués (février, décembre)
binmode(STDOUT, ":utf8");

# Récupération de la date
my $date = strftime($format, localtime());

# On s'assure que tout est en minuscules, puis on met 
# la première lettre de chaque mot en majuscule (pour le mois).
# Le s/(\w+)/\u$1/g transforme "07 mars 2026" en "07 Mars 2026"
$date =~ s/([a-zA-Záàâäéèêëíìîïóòôöúùûüç]+)/\u$1/g;

print "$date\n";
